add Swift 4.0 badge
alfa-laboratory/YARCH-Examples pull request #12
Opened 2017-12-27 16:01 UTC by imJustik

Update README.md

2017-12-27 17:45 UTC, aeternas submitted a review, later dismissed

2017-12-28 09:01 UTC, iltsarev requested changes
You also need to update README-rus.md

2017-12-28 12:02 UTC, aeternas approved these changes

2017-12-28 13:01 UTC, khramtsoff approved these changes

2017-12-28 14:28 UTC, iltsarev approved these changes

2017-12-28 14:28 UTC, merged