add LoadingTableViewDataSource tests
alfa-laboratory/YARCH-Examples pull request #13
Opened 2018-01-01 23:00 UTC by imJustik

*  remove dequeueReusable methods from UITableView extension
*  add LoadingTableViewDataSource tests

2018-01-09 09:15 UTC, iltsarev submitted a review, later dismissed

2018-01-09 09:31 UTC, xzeror submitted a review, later dismissed
Needs some minor fixes.

2018-01-09 09:31 UTC, xzeror commented on YARCH/Sources/LoadingTableView/Tests/LoadingTableViewDataSourceTests.swift
> +            it("shoud register cell class") {
typo: shoud -> should

2018-01-09 09:31 UTC, xzeror commented on YARCH/Sources/LoadingTableView/Tests/LoadingTableViewDelegateTests.swift
> +            it("shoud return height of section") {
typo: shoud -> should

2018-01-09 09:31 UTC, xzeror commented on YARCH/Sources/LoadingTableView/Tests/LoadingTableViewDelegateTests.swift
> +            it("shoud return height of section") {
I believe it must be "should return height of section header"

2018-01-09 09:31 UTC, xzeror commented on YARCH/Sources/Modules/Catalog/CatalogTableDataSource.swift
> +        guard let viewModel = representableViewModels[safe: indexPath.row],
Using guard here brings duplication of return statement. I think that using if statement will look more cleaner. Compare:
```
if let viewModel = representableViewModels[safe: indexPath.row],
   let catalogCell = cell as? CatalogCell {
    catalogCell.configure(cellRepresentable: viewModel)
}
return cell
```

2018-01-10 07:10 UTC, khramtsoff requested changes
Remove `tableView.register` from `cellForRow`, `viewForHeaderInSection`; apply type omission.

2018-01-10 07:10 UTC, khramtsoff commented on YARCH/Helpers/Extensions/UITableViewExtention.swift
>      convenience init(delegate: UITableViewDelegate, dataSource: UITableViewDataSource, backgroundColor: UIColor = UIColor.white, estimatedRowHeight: CGFloat = 80) {
UIColor.white - use type omission

2018-01-10 07:10 UTC, khramtsoff commented on YARCH/Sources/LoadingTableView/LoadingTableViewDataSource.swift
> +        tableView.register(LoadingTableViewCell.self, forCellReuseIdentifier: String(describing: LoadingTableViewCell.self))
performance issue

2018-01-10 07:10 UTC, khramtsoff commented on YARCH/Sources/LoadingTableView/LoadingTableViewDelegate.swift
> +        tableView.register(LoadingSectionHeaderView.self, forHeaderFooterViewReuseIdentifier: String(describing: LoadingSectionHeaderView.self))
performance issue

2018-01-10 07:10 UTC, khramtsoff commented on YARCH/Sources/Modules/Catalog/CatalogTableDataSource.swift
> +        tableView.register(CatalogCell.self, forCellReuseIdentifier: String(describing: CatalogCell.self))
performance issue

2018-01-10 07:58 UTC, imJustik commented on YARCH/Sources/LoadingTableView/LoadingTableViewDataSource.swift
> +        tableView.register(LoadingTableViewCell.self, forCellReuseIdentifier: String(describing: LoadingTableViewCell.self))
Nope

2018-01-10 07:58 UTC, imJustik commented on YARCH/Sources/LoadingTableView/LoadingTableViewDelegate.swift
> +        tableView.register(LoadingSectionHeaderView.self, forHeaderFooterViewReuseIdentifier: String(describing: LoadingSectionHeaderView.self))
Nope

2018-01-10 07:58 UTC, imJustik commented on YARCH/Sources/Modules/Catalog/CatalogTableDataSource.swift
> +        tableView.register(CatalogCell.self, forCellReuseIdentifier: String(describing: CatalogCell.self))
Nope

2018-01-10 08:30 UTC, closed without merging